# Grafana datasource configuration for Prometheus

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      cacheLevel: 'High'
      disableMetricsLookup: false
      customQueryParameters: ''
      timeInterval: '5s'
      queryTimeout: '60s'
      defaultEditor: 'code'
      disableRecordingRules: false
      incrementalQuerying: false
      incrementalQueryOverlapWindow: '10m'
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
    uid: prometheus-uid