name: Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please provide details below.

  - type: textarea
    id: question
    attributes:
      label: What's your question?
      description: Please be as specific as possible.
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What category does your question fall into?
      options:
        - Installation/Setup
        - Usage/Configuration
        - Carbon tracking methodology
        - Integration issues
        - Performance concerns
        - Visualization/dashboards
        - Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        Please provide relevant context:
        - What are you trying to achieve?
        - What have you already tried?
        - Any relevant code snippets
      render: python

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: |
        If your question is environment-specific, please provide:
      value: |
        - OS: [e.g. Ubuntu 20.04]
        - Python version: [e.g. 3.10.8]
        - Package version: [e.g. 0.1.0]
        - Relevant hardware: [e.g. NVIDIA RTX 3080]

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have checked the documentation
          required: true
        - label: I have searched existing issues for similar questions
          required: true