# Prometheus configuration for HF Eco2AI Plugin monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Rule files
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # HF Eco2AI Plugin metrics
  - job_name: 'hf-eco2ai-plugin'
    static_configs:
      - targets: ['hf-eco2ai:9091']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # GPU metrics (if available)
  - job_name: 'nvidia-gpu'
    static_configs:
      - targets: ['gpu-exporter:9445']
    scrape_interval: 5s
    honor_labels: true

# Remote write configuration for long-term storage
remote_write:
  - url: "http://victoriametrics:8428/api/v1/write"
    queue_config:
      max_samples_per_send: 10000
      batch_send_deadline: 5s
      min_shards: 1
      max_shards: 200

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
      timeout: 10s

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true